version: "3.9"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - cunewbie-search-poc-network
    volumes:
      - ./src:/app/src
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=123456
    ports:
      - 9200:9200
    networks:
      - cunewbie-search-poc-network

volumes:
  certs:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  cunewbie-search-poc-network:
    name: cunewbie-search-poc-network
