FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod go.sum ./

COPY ./src ./src

RUN go mod download

# auto reload for Go
RUN go install github.com/cosmtrek/air@latest

CMD ["air", "--build.cmd", "go build -o ./tmp/main ./src"]
