version: "3.9"

services:
  #  backend:
  #    container_name: backend
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    restart: on-failure
  #    networks:
  #      - cunewbie-search-poc-network
  #    volumes:
  #      - ./src:/app/src
  #    depends_on:
  #      mysql:
  #        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:8.0.32-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cunewbie-search-poc
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - cunewbie-search-poc-network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -P 3306 -u root --password=123456
      interval: 10s
      timeout: 5s
      retries: 10

  logstash:
    container_name: logstash
    image: logstash:8.6.2
    restart: unless-stopped
    environment:
      - LOGSTASH_JAVA_OPTS=-Xmx512m -Xms512m
    volumes:
      - ./config/logstash:/usr/share/logstash/config
      - ./config/logstash:/usr/share/logstash/pipeline
      - logstash_data:/usr/share/logstash/data
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  logstash_data:

networks:
  cunewbie-search-poc-network:
    name: cunewbie-search-poc-network
