FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod go.sum air.toml ./

COPY ./src ./src

RUN go mod download

# auto reload for Go
RUN go install github.com/cosmtrek/air@latest

CMD ["air", "-c", "air.toml"]

