version: "3.9"

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: on-failure
    networks:
      - cunewbie-search-poc-network
    volumes:
      - ./src:/app/src


networks:
  cunewbie-search-poc-network:
    name: cunewbie-search-poc-network
