
version: "3.9"

services:
  #  search:
  #    container_name: search
  #    build:
  #      context: .
  #      dockerfile: Dockerfile-dev
  #    restart: on-failure
  #    ports:
  #      - 3001:3001
  #    networks:
  #      - cunewbie-search-poc-network
  #    volumes:
  #      - ./src:/app/src
  #    depends_on:
  #      elasticsearch:
  #        condition: service_healthy
  #
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: unless-stopped
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=123456
    ports:
      - "9200:9200"
    networks:
      - cunewbie-search-poc-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  logstash:
    image: logstash:8.6.2
    container_name: logstash-elasticsearch
    restart: unless-stopped
    environment:
      - LOGSTASH_JAVA_OPTS=-Xmx512m -Xms512m
    volumes:
      - ./config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logstash_data:/usr/share/logstash/data
    ports:
      - "5001:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - cunewbie-search-poc-network

volumes:
  elasticsearch_data:
  logstash_data:

networks:
  cunewbie-search-poc-network:
    name: cunewbie-search-poc-network